# -*- coding: utf-8 -*-
"""Euclides.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgE93WQusrHMLSzzc016nwl7uKykijoc
"""

def extended_gcd_with_steps(a, b):
    """
    Implementa el algoritmo extendido de Euclides mostrando los pasos de la división.
    Encuentra mcd(a, b) y los coeficientes x e y tales que ax + by = mcd(a, b).
    """
    if b == 0:
        return a, 1, 0
    else:
        q = a // b
        r = a % b
        #print(f"{a} = {q} * {b} + {r}")
        gcd, x, y = extended_gcd_with_steps(b, r)
        return gcd, y, x - q * y

# Ejemplo de uso:
a = 4864
b = 3458
gcd, x, y = extended_gcd_with_steps(a, b)
print(f"\nEl mcd({a}, {b}) es {gcd}")
print(f"Los coeficientes x e y son: x = {x}, y = {y}")
print(f"Verificación: {a}*{x} + {b}*{y} = {a*x + b*y} = {gcd}")